I1109 20:38:40.983881 69648 controller.py:84] 1 processes started on host 0.0.0.0
I1109 20:38:40.991089 69648 _internal.py:87]  * Running on http://0.0.0.0:10038/ (Press CTRL+C to quit)
I1109 20:38:40.993184 69648 _internal.py:87]  * Restarting with stat
I1109 20:38:41.178973 69651 controller.py:84] 1 processes started on host 0.0.0.0
I1109 20:39:36.623502 69651 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:39:36] "GET / HTTP/1.1" 200 -
I1109 20:39:37.104181 69651 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:39:37] "GET /favicon.ico HTTP/1.1" 404 -
I1109 20:39:55.970113 69651 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:39:55] "GET /error_code HTTP/1.1" 200 -
I1109 20:40:14.131114 69651 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/controller.py', reloading
I1109 20:40:14.157172 69648 _internal.py:87]  * Restarting with stat
I1109 20:40:14.568233 69678 controller.py:82] 1 processes started on host 0.0.0.0
I1109 20:40:22.794466 69678 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:40:22] "GET / HTTP/1.1" 200 -
E1109 20:41:13.985644 69678 worker.py:50] App:Image2Vector parse data error
I1109 20:41:13.985883 69678 controller.py:64] 1: 0
I1109 20:41:13.986555 69678 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:41:13] "GET /query?id=1 HTTP/1.1" 200 -
I1109 20:42:20.922354 69678 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/controller.py', reloading
I1109 20:42:20.937783 69648 _internal.py:87]  * Restarting with stat
I1109 20:42:21.301935 69712 controller.py:83] 1 processes started on host 0.0.0.0
I1109 20:42:35.642321 69728 controller.py:83] 1 processes started on host 0.0.0.0
I1109 20:42:35.644686 69728 _internal.py:87]  * Running on http://0.0.0.0:10038/ (Press CTRL+C to quit)
I1109 20:42:35.645435 69728 _internal.py:87]  * Restarting with stat
I1109 20:42:35.807641 69731 controller.py:83] 1 processes started on host 0.0.0.0
E1109 20:42:42.174938 69731 worker.py:50] App:Image2Vector parse data error
I1109 20:42:42.175273 69731 controller.py:65] 1: 0
I1109 20:42:42.175856 69731 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:42:42] "GET /query?id=1 HTTP/1.1" 200 -
I1109 20:44:27.999454 69731 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/controller.py', reloading
I1109 20:44:28.016742 69728 _internal.py:87]  * Restarting with stat
I1109 20:44:28.313302 69762 controller.py:79] 1 processes started on host 0.0.0.0
I1109 20:46:20.437124 69762 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/controller.py', reloading
I1109 20:46:20.453551 69728 _internal.py:87]  * Restarting with stat
I1109 20:46:20.804577 69791 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:46:29.315809 69806 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:46:29.318273 69806 _internal.py:87]  * Running on http://0.0.0.0:10038/ (Press CTRL+C to quit)
I1109 20:46:29.318922 69806 _internal.py:87]  * Restarting with stat
I1109 20:46:29.482779 69809 controller.py:80] 1 processes started on host 0.0.0.0
E1109 20:46:35.031522 69809 worker.py:50] App:Image2Vector parse data error
I1109 20:46:35.031769 69809 controller.py:62] 1: 0
I1109 20:46:35.032341 69809 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:46:35] "GET /query?id=1 HTTP/1.1" 200 -
I1109 20:47:31.161794 69809 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/app/img_to_vector_app.py', reloading
I1109 20:47:31.175630 69806 _internal.py:87]  * Restarting with stat
I1109 20:47:31.459702 69836 controller.py:80] 1 processes started on host 0.0.0.0
E1109 20:47:37.267870 69836 worker.py:50] App:Image2Vector parse data error
I1109 20:47:37.268063 69836 controller.py:62] 1: 0
I1109 20:47:37.268488 69836 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:47:37] "GET /query?id=1 HTTP/1.1" 200 -
I1109 20:47:58.765830 69836 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/app/img_to_vector_app.py', reloading
I1109 20:47:58.787648 69806 _internal.py:87]  * Restarting with stat
I1109 20:47:59.181030 69848 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:48:02.307384 69862 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:48:02.309760 69862 _internal.py:87]  * Running on http://0.0.0.0:10038/ (Press CTRL+C to quit)
I1109 20:48:02.310339 69862 _internal.py:87]  * Restarting with stat
I1109 20:48:02.527966 69865 controller.py:80] 1 processes started on host 0.0.0.0
E1109 20:48:05.421055 69865 worker.py:50] App:Image2Vector parse data error
I1109 20:48:05.421289 69865 controller.py:62] 1: 0
I1109 20:48:05.421840 69865 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:48:05] "GET /query?id=1 HTTP/1.1" 200 -
I1109 20:48:44.942672 69865 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/app/img_to_vector_app.py', reloading
I1109 20:48:44.958997 69862 _internal.py:87]  * Restarting with stat
I1109 20:48:45.203126 69881 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:48:50.580106 69896 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:48:50.582386 69896 _internal.py:87]  * Running on http://0.0.0.0:10038/ (Press CTRL+C to quit)
I1109 20:48:50.583081 69896 _internal.py:87]  * Restarting with stat
I1109 20:48:50.759706 69899 controller.py:80] 1 processes started on host 0.0.0.0
E1109 20:48:55.934175 69899 worker.py:50] App:Image2Vector parse data error
I1109 20:48:55.934422 69899 controller.py:62] 1: 0
I1109 20:48:55.934956 69899 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:48:55] "GET /query?id=1 HTTP/1.1" 200 -
I1109 20:49:08.975708 69899 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/app/img_to_vector_app.py', reloading
I1109 20:49:09.051301 69896 _internal.py:87]  * Restarting with stat
I1109 20:49:09.330754 69910 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:49:13.567084 69924 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:49:13.569997 69924 _internal.py:87]  * Running on http://0.0.0.0:10038/ (Press CTRL+C to quit)
I1109 20:49:13.570861 69924 _internal.py:87]  * Restarting with stat
I1109 20:49:13.746361 69928 controller.py:80] 1 processes started on host 0.0.0.0
E1109 20:49:19.329660 69928 worker.py:50] App:Image2Vector parse data error
I1109 20:49:19.329926 69928 controller.py:62] 1: 0
I1109 20:49:19.330606 69928 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:49:19] "GET /query?id=1 HTTP/1.1" 200 -
E1109 20:49:22.814527 69928 worker.py:50] App:Image2Vector parse data error
I1109 20:49:22.814806 69928 controller.py:62] 1: 0
I1109 20:49:22.815248 69928 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:49:22] "GET /query?id=1 HTTP/1.1" 200 -
E1109 20:49:24.836802 69928 worker.py:50] App:Image2Vector parse data error
I1109 20:49:24.836998 69928 controller.py:62] 1: 0
I1109 20:49:24.837547 69928 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:49:24] "GET /query?id=1 HTTP/1.1" 200 -
E1109 20:49:28.944555 69928 worker.py:50] App:Image2Vector parse data error
I1109 20:49:28.944904 69928 controller.py:62] 2: 0
I1109 20:49:28.945365 69928 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:49:28] "GET /query?id=2 HTTP/1.1" 200 -
I1109 20:50:28.534708 69928 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/app/img_to_vector_app.py', reloading
I1109 20:50:28.551935 69924 _internal.py:87]  * Restarting with stat
I1109 20:50:28.878607 69960 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:50:31.986057 69974 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:50:31.988245 69974 _internal.py:87]  * Running on http://0.0.0.0:10038/ (Press CTRL+C to quit)
I1109 20:50:31.988925 69974 _internal.py:87]  * Restarting with stat
I1109 20:50:32.213274 69977 controller.py:80] 1 processes started on host 0.0.0.0
E1109 20:50:36.552900 69977 worker.py:50] App:Image2Vector parse data error
I1109 20:50:36.553246 69977 controller.py:62] 2: 0
I1109 20:50:36.553819 69977 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:50:36] "GET /query?id=2 HTTP/1.1" 200 -
E1109 20:50:39.769031 69977 worker.py:50] App:Image2Vector parse data error
I1109 20:50:39.769283 69977 controller.py:62] 1: 0
I1109 20:50:39.769710 69977 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:50:39] "GET /query?id=1 HTTP/1.1" 200 -
E1109 20:50:53.042071 69977 worker.py:50] App:Image2Vector parse data error
I1109 20:50:53.042304 69977 controller.py:62] 1: 0
I1109 20:50:53.042699 69977 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:50:53] "GET /query?id=1 HTTP/1.1" 200 -
I1109 20:51:50.989895 69977 _internal.py:87]  * Detected change in '/Users/David/Desktop/Gatech/BDS/project/server/app/img_to_vector_app.py', reloading
I1109 20:51:51.023542 69974 _internal.py:87]  * Restarting with stat
I1109 20:51:51.318974 70080 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:51:57.467864 70094 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:51:57.470254 70094 _internal.py:87]  * Running on http://0.0.0.0:10038/ (Press CTRL+C to quit)
I1109 20:51:57.470856 70094 _internal.py:87]  * Restarting with stat
I1109 20:51:57.641238 70097 controller.py:80] 1 processes started on host 0.0.0.0
I1109 20:52:02.007469 70097 controller.py:62] 1: https://amazon.com/id=1
I1109 20:52:02.008297 70097 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:52:02] "GET /query?id=1 HTTP/1.1" 200 -
I1109 20:52:11.552870 70097 controller.py:62] 2: https://amazon.com/id=2
I1109 20:52:11.553378 70097 _internal.py:87] 127.0.0.1 - - [09/Nov/2017 20:52:11] "GET /query?id=2 HTTP/1.1" 200 -
